import Head from 'next/head'
import 'normalize.css';
import Header from "@/components/header";
import { Roboto } from '@next/font/google';
import SiteBody from "@/components/siteBody";
import React from "react";
import EmptyEntry from "@/components/emptyEntry";
import Style from '../styles/style.module.scss';
import classNames from "classnames";
import {Provider} from "react-redux";
import store from "@/states/store";
import ErrorPhoto from '../svg/Error.svg';


const roboto = Roboto({
    weight: '400',
    subsets: ['latin']
});

const Home = ({entry, error}) => {
  return (
      <Provider store={store}>
          <>
              {error
                  ? <EmptyEntry image={ErrorPhoto} text="Ошибка сервера или сервер оффлайн" />
                  :
                  <>
                      <Head>
                          <title>Summer</title>
                          <meta name="description" content="Generated by create next app" />
                          <meta name="viewport" content="width=device-width, initial-scale=1" />
                          <link rel="icon" href="/favicicon.svg" />
                      </Head>
                      <main className={classNames(roboto.className, Style.main)}>
                          <Header />
                          <SiteBody nameDataEntry={entry} />
                      </main>
                  </>
              }
          </>
      </Provider>
  )
}
export default Home;

export async function getStaticProps() {
    try {
        const response = await fetch("http://ec2-3-8-33-223.eu-west-2.compute.amazonaws.com:8000/api/entry");
        const entry = await response.json();

        return {
            props: {entry},
        }
    } catch (e) {
        console.log(e)
        return {
            props: {
                error: 'Error'
            }
        }
    }
}
